### ISSUE TITLE
Pretty URL's

### ISSUE THREAD

**Issue by tehmaestro** [Kerry350/ember-deploy-s3-index#11]
Hi, I'm looking into deploying my app to amazon, and it seems that a lot of people recommend putting it in S3. 

My question is, being that this is an Ember App, how will URL's work? Is the use of hashtags mandatory in this case, or is there a way to redirect all requests to index.html ?

 Thanks.

**Comment by LevelbossMike** [comment]
Hi @tehmaestro I wanted to update the README accordingly but didn't find the time to do so yet:

You can use the redirection rules to get s3 hosting working with the auto location ember-cli gives you out of the box. Here's a small example:

```
<RoutingRules>
    <RoutingRule>
        <Condition>
            <HttpErrorCodeReturnedEquals>404</HttpErrorCodeReturnedEquals>
        </Condition>
        <Redirect>
            <HostName><your-bucket-name>.s3-website-us-east-1.amazonaws.com</HostName>
            <ReplaceKeyPrefixWith>#/</ReplaceKeyPrefixWith>
        </Redirect>
    </RoutingRule>
</RoutingRules>
```

I will create a pull request tomorrow that illustrates this a bit better. Maybe add some screenshots etc. but this should setup everything correctly.

**Comment by tehmaestro** [comment]
Very cool. Thanks so much.

**Comment by Kerry350** [comment]
Closing this off now that the documentation is in the README, thanks everyone :+1:
