### ISSUE TITLE
PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint.

### ISSUE THREAD

**Issue by radcliff** [Kerry350/ember-deploy-s3-index#20]
i am trying to `ember deploy:list --environment production` and getting `PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.`

i managed to `console.log` the complete error which shows:

```
{ Code: 'PermanentRedirect',
  Message: 'The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.',
  Bucket: 'my.bucket',
  Endpoint: 'my.bucket.s3.amazonaws.com',
  RequestId: 'xxx',
  HostId: 'xxx' }
```

i believe this error is due to the fact that my bucket name contains a `.` but i'm not sure. 

```
# config/deploy.js

module.exports = {
  production: {
    store: {
      type: "S3",
      accessKeyId: process.env.S3_ACCESS_KEY_ID,
      secretAccessKey: process.env.S3_SECRET_ACCESS_KEY,
      bucket: 'my.bucket',
      acl: 'public-read',
      hostName: 'my.bucket.s3-website-us-west-1.amazonaws.com',
      indexMode: 'direct',
      prefix: ''
    },

    assets: {
      type: "s3",
      accessKeyId: process.env.S3_ACCESS_KEY_ID,
      secretAccessKey: process.env.S3_SECRET_ACCESS_KEY,
      bucket: 'my.bucket'
    }
  }
}
```

thanks!

**Comment by johnnyshields** [comment]
This could be related to the S3 region not being specified (sometimes AWS requires the region explicitly even though it's already in the hostname). I've seen a similar error in a different library.

**Comment by timiyay** [comment]
@radcliff Did you end up resolving this?

I'm getting a similar issue, and I'm currently assuming I'm misunderstanding the `hostName` value I'm supposed to use. A quick Google points to this issue being for non-US regions (I'm in ap-southeast-2), but all variations on the `hostName` are throwing the same error for me.

Am I supposed to be using the full s3 static site host name? (i.e. `ember.index.s3-website-ap-southeast-2.amazonaws.com`)

Not only does `ember deploy:list` fail, but so does the index / store deployment. The assets works, but the index bucket is not updated.

UPDATE: some digging showed that my issue occurs when my non-US bucket name has periods in it. This means it's likely related to https://github.com/Kerry350/ember-deploy-s3-index/issues/25

I'll keep digging, as it appears to be related to https://github.com/aws/aws-sdk-js/issues/285 which, in turn, pushes the blame down to the S3 API.

The requirements of S3 static website hosting, where the bucket name matches the domain name, require periods.

**Comment by timiyay** [comment]
Solved.

You have to specify `region` in your config, which is transparently passed down to `aws-sdk`, which passes it to the S3 API. Otherwise, the region is set as `us-east-1`, and the redirect comes back.

Example:

``` js
store: {
  type: 'S3',
  bucket: 'ember.index',
  accessKeyId: xxxxxxxxxxxxxxx,
  secretAccessKey: xxxxxxxxxxxxxxx,
  hostName: 'ember.index.s3-website-ap-southeast-2.amazonaws.com',
  indexMode: 'direct'
}
```
