### ISSUE TITLE
Fails silently when bucket name contains a period

### ISSUE THREAD

**Issue by Truffula** [Kerry350/ember-deploy-s3-index#25]
If the bucket is, say, `prototype.foo-bar`, deploying shows the message "Trying to upload `dist/index.html`..." then it fails silently.

**Comment by timiyay** [comment]
I encountered this issue as well, within a different context. It's related to the error in https://github.com/Kerry350/ember-deploy-s3-index/issues/20.

Changing to a bucket name without periods sidestepped the issue temporarily, but S3 static website hosting requires bucket names that match the domain, which means periods are essential.

Related issue from `aws-sdk` repo: https://github.com/aws/aws-sdk-js/issues/285

**Comment by timiyay** [comment]
Solved. See my comment on a related issue: https://github.com/Kerry350/ember-deploy-s3-index/issues/20#issuecomment-150104273
